[package]
name = "tui-utils"
version = "0.1.0"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
