[package]
name = "tui-utils"
version = "0.5.1"
authors = ["Acizza <jgit@tuta.io>"]
edition = "2018"

[dependencies]
smallvec = "1.6"
unicode-segmentation = "1.7"
unicode-width = "0.1"

[dependencies.tui]
version = "0.14"
default-features = false
